---
title: "PEER Network School 2023"
draft: no
date: "2020-07-20T00:00:00Z"
lastmod: "2020-07-20T00:00:00Z"
linktitle: PEER Network School
menu:
  peer_network_school:
    name: PEER Network School
    weight: 1
summary: 2023 PEER Advanced Field School on Social Network Analysis
type: docs
weight: 1
---

Welcome to this PEER Advanced Network School. First, thanks to Scott Franklin, Ellie Sayre, Mary Bridget Kustusch and the PEER team for supporting this field school!

### The Plan
The main idea is to have some time learning about different aspects of Social Network Analysis, and to actually focus on doing the analyses. We will spend the mornings working on learning aspects of SNA, and then the afternoons will be working time, where we actually try to carry out some of the types of analyses on your own data. 

|Topics| Date|
|------|------|
|Network Theory and Data| 26 June 2023|
|Individuals within networks |27 June 2023|
|Properties of whole networks |28 June 2023|
|Network models |29 June 2023|
|Projects |30 June 2023|


### What might you learn?
There are lots of things that I hope you would learn: to look at the complexity of Social Networks, to use R tools to look at networks, to read code, to write code, to find that you are not afraid (and actually like) to analyze data with R. By the end of all three sessions here are things I think you should be able to do after participating in each of the workshops:

**Day One**



[Day 1 Slides](<https://ericbrewe.com/slides/PEER_network_school_2023/PEER_network_theory.html#1>)

* Import Data into R
* Clean data and prepare data for SNA
* Organize data for SNA
* Vizualize data

**Day Two**


[Day 2 Slides](<https://ericbrewe.com/slides/PEER_network_school_2023/PEER_Individuals_Networks.html#1>)

* Understand different centrality metrics 
* Plotting networks and incorporating centrality


**Day Three**


[Day 3 Slides](<https://ericbrewe.com/slides/PEER_network_school_2023/PEER_whole_networks.html#1>)

* Understand different metrics about whole networks
* Community Detection


[Day 3a Slides](<https://ericbrewe.com/slides/PEER_network_school_2023/PEER_bipartite_graphs.html#1>)

* Side trip to visit bipartite networks.

**Day Four**


[Day 4 Slides](<https://ericbrewe.com/slides/PEER_network_school_2023/PEER_network_models.html#1>)

* Understand the framework for comparing networks
* Test hypotheses in a network framework

### What is beyond the scope?
While I would love to say you'd be able to master doing network analysis in R in the short span of 1 week, you will not. I've spent a decade learning it and am proficient, but am constantly learning. 

Similarly, R is a tool. You are the expert in your research, R can help *you* to uncover elements of your data. I don't know how to analyze your data - learning R will empower you to analyze your data. 


### Why R?
I began learning R because I wanted to have something that worked across different platforms. But then I realized that the Open Source movement was something that was particularly interesting to me.  But those aren't the reason. I have come to see R as crucial for reproducibility. If I write a set of code to analyze a dataset, I can re-run this code, and get the same results. I can share the code with my publications, so someone else can check my work. This is critical to doing science. R allows me to do this in a way that Excel doesn't. 

Certainly other languages (Python, Julia, etc...) will also allow for this, but why I have stuck with R is that there is a rich community that are supportive of learning and growing. 

### Why Tidyverse?
Open source things tend to be a bit tribal - within R one debate is Base R vs. Tidyverse. This is a debate about how to teach R, and I have decided to use the Tidyverse. It might not ever matter to you, but I want you to know that I have thought about this, and my answer is to use Tidyverse for the following reasons:

- Readability - Code should be readable by humans
- Coherence with my practice - I generally try to use the Tidyverse approach in my work, so I feel like I can best help by using these tools
- Coherence with themselves - These tools are organized in a way that helps them to be internally coherent
- Support - There are loads of books and websites that are published open-source, and so you can typically find the help you need. 


### Resources for Learning R
Learning R is not easy, as I have learned things, I have tried to maintain a list of the different resources that I have drawn on. 

**The Basics**

1. Install R and RStudio
2. Introduction to R (using Base R) - [R Programming for Data Science](<https://bookdown.org/rdpeng/rprogdatascience/>)
3. My all time favorite book for learning statistics and R is [Learning Statistics with R](<http://tidylsr.djnavarro.net/>)
4. Danielle Navarro also has a course [Robust Tools](<http://robust-tools.djnavarro.net/>) that gives a sense about the breadth of the tools that R provides.
5. These two guides, [The R Guide](<https://drive.google.com/file/d/1G9rqsXdesobxbWivbrD1MN0K97jMNEST/view>) and [R for Beginners](<https://drive.google.com/file/d/1jUivTK7z3Ig_51upZ4mD5l2v-PCXOoGp/view>)

**A bit more advanced**

1. Hadley Wickham's book, [R For Data Science](<https://r4ds.had.co.nz/>)
2. [Project Oriented Workflows](<https://www.tidyverse.org/blog/2017/12/workflow-vs-script/>)
3. [WTF R](<https://rstats.wtf/index.html>) Jenny Bryan is great at explaining things about R and so frequently, I find myself looking at her books.
4. [Cheat Sheets](<https://rstudio.com/resources/cheatsheets/>) I can never remember all the commands. 
    a. [Data Transformation](<file:///Users/ericbrewelaptop/Downloads/data-transformation.pdf>)
    b. [ggplot2](<https://github.com/rstudio/cheatsheets/raw/master/data-visualization-2.1.pdf>)
    c. [Regular Expressions](<https://github.com/rstudio/cheatsheets/raw/master/data-visualization-2.1.pdf>)
5. [Happy Git With R](<https://happygitwithr.com/>) Eventually you'll need to use Git, and this is essential reading for making that transition.
6. [RMarkdown](<https://bookdown.org/yihui/rmarkdown/software-info.html>) Markdown allows you to use reproducible code and integrate R into reporting and writing. This is how I do all my work. 
7. [DataCarpentry](<https://datacarpentry.org/>) runs workshops about data analysis and often are oriented to different research specialties. 
8. [The Effect](<https://theeffectbook.net/>) A really great book that approaches data analysis from a causal inference perspective with code in R, Python, and Stata.


### Resources for Learning SNA

# Books 
- [Wasserman and Faust](<https://www.cambridge.org/core/books/social-network-analysis/90030086891EB3491D096034684EFFB8>) The seminal text on social networks from the sociological camp. No help with R, but includes so much that it is an essential reference.
- [Newman](<https://academic.oup.com/book/27884>) Don't know if I would call it *the* seminal text on networks from the graph-theoretic camp. No help with R. If you want to have access to the mathematical underpinnigs, this one has it (probably).
- [Barabasi](<http://networksciencebook.com/>) A newer text, it is available to read online, with some animations, cool visuals, etc. Focus on python I think.
- [Sage Handbook](<https://uk.sagepub.com/en-gb/eur/the-sage-handbook-of-social-network-analysis/book232753>). A comprehensive guide to doing SNA - has chapters on IRB, network generators, analytic approaches and more. Plus if you want to read about the two camps from a sociologist's perspective, chapter four is not particularly kind to physicists. 

# Websites that are useful
- [tidygraph](<https://tidygraph.data-imaginist.com/index.html>) enough said
- [ggraph](<https://ggraph.data-imaginist.com/>) enough said
- [mr.stochastics](<https://www.mr.schochastics.net/>) Excellent explainers on visualization, and tutorials on doing SNA.

# Societies, Journals, and Meetings

## Professional Societies
- [International Network of Social Network Analysis](<https://www.insna.org/>) - Much more from the Social Network, social science side
- [Network Science Society](<https://netscisociety.net/home>) - The professional society that hosts NetSci - a premier network analysis conference, much more from the graph/theoretic world

## Journals
- [Network Science](<https://www.cambridge.org/core/journals/network-science>) - Cambridge Press Journal focused on Network Science - much more graph theoretic
- [Connections](<https://www.insna.org/connections>) - The journal of INSNA - much more focused on social network analysis & applications. 
- [Social Networks](<https://www.sciencedirect.com/journal/social-networks>) - An Elsevier Journal focused on SNA - much more statistical

## Meetings
- [Sunbelt](<https://www.insna.org/events/sunbelt-2023>) - Conference of INSNA
- [NetSci](<https://netsci2023.wixsite.com/netsci2023>) - Conference of Network Science Society
- [CompleNet](<https://complenet.weebly.com/>) - International Conference on Complex Networks

# Datasets
- [Colorado Index of Complex Networks](<https://icon.colorado.edu/#!/>) - Maintained by Aaron Clauset - very high quality datasets
- [Stanford Large Network Datasets](<https://snap.stanford.edu/data/>) - Maintained by Stanford - a list, not necessarily as clean, but a large list


