---
title: Standards Based Grading With Gradescope 
author: Eric Brewe
date: '2020-04-22'
slug: Standars Based Grading
categories:
  - PHYS 115
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2020-04-15T11:29:23-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

My plan for this course has been to use standards based grading on weekly assignments. The basic theory of this practice is that we should be assessing students on their understanding, so this means that they have to demonstrate said understanding. They do this in my class by submitting weekly homework (not a big deal). The big difference in standards-based grading is that each problem is evaluated on a standardized rubric. 

I need a rubric. But I also know that websites like [Chegg](https://www.chegg.com/) make it super easy to find answers to textbook problems. So a rubric that just evaluates answers may not ensure that students are demonstrating understanding. The rubric I have developed then focuses on explanation of their solutions. It is here:

| Score | Meaning |
| ---------------------| ----------------------------------------------- |
| 4 | Fully complete, well explained, all work shown, correct answer someone could pick up this solution and read it.|
| 3 | Complete, explained adquately, work shown, correct answer. Someone would probably understand this solution. |
| 2 | Missing either adequate explanation or work, answer is correct, but someone would struggle to understand what you've done to get to this solution.|
| 1 | Missing either adequate explanation or work and answer is incorrect. |
| 0 | No or very little effort demonstrated |

Then the students' grades are determined based on the proportion of the problems that are evaluated as satisfactory. So for example, if a student submits 100\% of the problems, but only 85\% are evaluated as satisfactory, then that student would have an 85\%. Another student who submits only 80\% of the problems but every problem submitted is evaluated as satisfactory would get an 80\%. 

This grading scheme is interesting becasue it is not what physics majors have typically experienced.  They are used to solving problems and focusing on right answers. It is possible for a student to have correctly solved every problem, but have not explained anything (meaning no words), and that student will have a 0\%! One of the biggest challenges I have is helping students to break this habit of submitting solutions without any explanation. 

That is not the end though. Because the goal is for students to achieve standards, I also allow for students to resubmit work (up to 9 times). This helps to alleviate the issue of students who have solved problems correctly, but haven't explained. Go back, explain, and resubmit. You can take a 0\% to a 100\% fairly efficiently. Hopefully, it encourages students to review their feedback and consider the work they have submitted - at least that is the ideal.  Currently, it feels like about 1/3 of the class is fully on board - including explanations and writing up work thoroughly and many times beautifully. One third has not used a single word in any of their problems - so we talked aobut this in class today. And the middle third hasn't quite calibrated their explanations, sometimes they are doing it effectively and sometimes not. 

This process is interesting, I am testing it at a small scale (16 students). I am evaluating relatively harshly in the beginning as I find that if I don't they won't come to the realization that they need to incorporate explanations. Gradescope makes this process pretty easy as I built the rubric one time and use it over and over for each problem. But that is a different post. 