---
title: "MatchingWSParticipants"
author: "Eric Brewe"
date: "8/3/2020"
output: html_document
---

```{r GetData}
pacman::p_load(tidyverse, here)

SignedUp = read_csv(here("static/slides/RForSNA/data","RForSNAWSList.csv"))
SurveyData = read_csv(here("static/slides/RForSNA/data","DataForWorkshopV.csv"))


SurveyData %>% 
  filter(DistributionChannel == "email") %>%
  rename(SurveyID = ResponseId, 
         Email = RecipientEmail) -> SurveyData

```


```{r MergeData}
Participants = left_join(SignedUp, SurveyData, by = "Email")

Participants %>%
  mutate(ID = sample(c(1000:10000), nrow(Participants))) %>%
  select(SurveyID, ID, Email, FullName) -> Participants

SignedUp %>%
  left_join(., Participants, by = c("Email", "FullName")) -> SignedUp

SurveyData %>%
  left_join(., Participants, by = c("SurveyID", "Email")) -> SurveyData
```


```{r GenerateAnonEL}
SurveyData %>%
  select(ID, FullName, Q7) %>%
  separate_rows(Q7, sep = ",") %>%
  left_join(., Participants %>% select(ID,FullName), by = c("Q7" = "FullName")) %>%
  mutate(Connections = as.character(ID.y), ID = as.character(ID.x)) %>%
  select(ID, Connections) -> AnonEL

write_csv(AnonEL, here("static/slides/RForSNA/data", "AnonEL.csv"))  
```


```{r GenerateAnonSurveyData}

SurveyData %>%
  select(ID, everything())%>%
  select(-c(RecipientFirstName, Email, RecipientLastName, IPAddress, LocationLongitude, LocationLatitude, Q7, FullName )) -> AnonSurveyData

write_csv(AnonSurveyData, here("static/slides/RForSNA/data", "AnonSurveyData.csv"))
```

